"""Update Interview Models

Revision ID: f28ec048d4c8
Revises: 181aa7b93df3
Create Date: 2026-03-21 19:57:48.929406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f28ec048d4c8'
down_revision: Union[str, Sequence[str], None] = '181aa7b93df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_sessions_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_interview_questions_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_interview_responses_id'), table_name='interview_responses')
    op.drop_table('interview_responses')
    op.drop_index(op.f('ix_smart_sentences_id'), table_name='smart_sentences')
    op.drop_table('smart_sentences')
    op.alter_column('answers', 'user_answer',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'user_answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_table('smart_sentences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weak_phrase', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('strong_phrase', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('smart_sentences_skill_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('smart_sentences_pkey'))
    )
    op.create_index(op.f('ix_smart_sentences_id'), 'smart_sentences', ['id'], unique=False)
    op.create_table('interview_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], name=op.f('interview_responses_question_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('interview_responses_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_responses_pkey'))
    )
    op.create_index(op.f('ix_interview_responses_id'), 'interview_responses', ['id'], unique=False)
    op.create_table('interview_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('difficulty_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('associated_skill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ideal_answer_points', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['associated_skill_id'], ['skills.id'], name=op.f('interview_questions_associated_skill_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_questions_pkey'))
    )
    op.create_index(op.f('ix_interview_questions_id'), 'interview_questions', ['id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('conducted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('interview_sessions_job_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('interview_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_sessions_pkey'))
    )
    op.create_index(op.f('ix_interview_sessions_id'), 'interview_sessions', ['id'], unique=False)
    # ### end Alembic commands ###
