"""added reset_code

Revision ID: fda8247fbfb5
Revises: 
Create Date: 2026-03-08 11:42:25.583584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fda8247fbfb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('course_skills_skill_id_fkey'), 'course_skills', type_='foreignkey')
    op.drop_constraint(op.f('course_skills_course_id_fkey'), 'course_skills', type_='foreignkey')
    op.create_foreign_key(None, 'course_skills', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'course_skills', 'skills', ['skill_id'], ['id'])
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_interview_questions_id'), 'interview_questions', ['id'], unique=False)
    op.create_index(op.f('ix_interview_responses_id'), 'interview_responses', ['id'], unique=False)
    op.drop_constraint(op.f('interview_responses_session_id_fkey'), 'interview_responses', type_='foreignkey')
    op.create_foreign_key(None, 'interview_responses', 'interview_sessions', ['session_id'], ['id'])
    op.alter_column('interview_sessions', 'conducted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_interview_sessions_id'), 'interview_sessions', ['id'], unique=False)
    op.drop_constraint(op.f('interview_sessions_user_id_fkey'), 'interview_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'interview_sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('job_skills_skill_id_fkey'), 'job_skills', type_='foreignkey')
    op.drop_constraint(op.f('job_skills_job_id_fkey'), 'job_skills', type_='foreignkey')
    op.create_foreign_key(None, 'job_skills', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(None, 'job_skills', 'skills', ['skill_id'], ['id'])
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.alter_column('resume_job_scores', 'missing_keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('resume_job_scores', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_resume_job_scores_id'), 'resume_job_scores', ['id'], unique=False)
    op.drop_constraint(op.f('resume_job_scores_job_id_fkey'), 'resume_job_scores', type_='foreignkey')
    op.drop_constraint(op.f('resume_job_scores_resume_id_fkey'), 'resume_job_scores', type_='foreignkey')
    op.create_foreign_key(None, 'resume_job_scores', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(None, 'resume_job_scores', 'resumes', ['resume_id'], ['id'])
    op.create_index(op.f('ix_resume_sections_id'), 'resume_sections', ['id'], unique=False)
    op.drop_constraint(op.f('resume_sections_resume_id_fkey'), 'resume_sections', type_='foreignkey')
    op.create_foreign_key(None, 'resume_sections', 'resumes', ['resume_id'], ['id'])
    op.drop_constraint(op.f('resume_skills_resume_id_fkey'), 'resume_skills', type_='foreignkey')
    op.drop_constraint(op.f('resume_skills_skill_id_fkey'), 'resume_skills', type_='foreignkey')
    op.create_foreign_key(None, 'resume_skills', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key(None, 'resume_skills', 'skills', ['skill_id'], ['id'])
    op.alter_column('resumes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('resumes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.drop_constraint(op.f('resumes_user_id_fkey'), 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'])
    op.alter_column('skills', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('skills_name_key'), 'skills', type_='unique')
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_index(op.f('ix_smart_sentences_id'), 'smart_sentences', ['id'], unique=False)
    op.add_column('users', sa.Column('reset_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_code_expire', sa.DateTime(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('users', 'reset_code_expire')
    op.drop_column('users', 'reset_code')
    op.drop_index(op.f('ix_smart_sentences_id'), table_name='smart_sentences')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.create_unique_constraint(op.f('skills_name_key'), 'skills', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('skills', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key(op.f('resumes_user_id_fkey'), 'resumes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.alter_column('resumes', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('resumes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'resume_skills', type_='foreignkey')
    op.drop_constraint(None, 'resume_skills', type_='foreignkey')
    op.create_foreign_key(op.f('resume_skills_skill_id_fkey'), 'resume_skills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('resume_skills_resume_id_fkey'), 'resume_skills', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'resume_sections', type_='foreignkey')
    op.create_foreign_key(op.f('resume_sections_resume_id_fkey'), 'resume_sections', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_resume_sections_id'), table_name='resume_sections')
    op.drop_constraint(None, 'resume_job_scores', type_='foreignkey')
    op.drop_constraint(None, 'resume_job_scores', type_='foreignkey')
    op.create_foreign_key(op.f('resume_job_scores_resume_id_fkey'), 'resume_job_scores', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('resume_job_scores_job_id_fkey'), 'resume_job_scores', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_resume_job_scores_id'), table_name='resume_job_scores')
    op.alter_column('resume_job_scores', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('resume_job_scores', 'missing_keywords',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.alter_column('jobs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'job_skills', type_='foreignkey')
    op.drop_constraint(None, 'job_skills', type_='foreignkey')
    op.create_foreign_key(op.f('job_skills_job_id_fkey'), 'job_skills', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('job_skills_skill_id_fkey'), 'job_skills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('interview_sessions_user_id_fkey'), 'interview_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_interview_sessions_id'), table_name='interview_sessions')
    op.alter_column('interview_sessions', 'conducted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'interview_responses', type_='foreignkey')
    op.create_foreign_key(op.f('interview_responses_session_id_fkey'), 'interview_responses', 'interview_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_interview_responses_id'), table_name='interview_responses')
    op.drop_index(op.f('ix_interview_questions_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_constraint(None, 'course_skills', type_='foreignkey')
    op.drop_constraint(None, 'course_skills', type_='foreignkey')
    op.create_foreign_key(op.f('course_skills_course_id_fkey'), 'course_skills', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('course_skills_skill_id_fkey'), 'course_skills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
